"""Minimal demonstration interface for the OpenTutorAI agentic prototype."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Dict, List

import streamlit as st


# ---------------------------------------------------------------------
# Repository imports
# ---------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ai.agentic.core.agentic_core_service import AgenticCoreService
from ai.llm.errors import LLMProviderUnavailableError


# ---------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------

st.set_page_config(
    page_title="OpenTutorAI Agentic Demo",
    page_icon="🧠",
    layout="centered",
)


# ---------------------------------------------------------------------
# Trace helpers
# ---------------------------------------------------------------------

def load_trace(trace_path_value: Any) -> Dict[str, Any]:
    """Load the Tool Interaction Trace generated by the workflow."""

    if not trace_path_value:
        return {}

    trace_path = Path(str(trace_path_value))

    if not trace_path.is_absolute():
        trace_path = REPO_ROOT / trace_path

    if not trace_path.exists() or not trace_path.is_file():
        return {}

    try:
        trace = json.loads(
            trace_path.read_text(encoding="utf-8")
        )
    except (OSError, json.JSONDecodeError):
        return {}

    return trace if isinstance(trace, dict) else {}


def collect_tools(
    response: Dict[str, Any],
    trace: Dict[str, Any],
) -> List[str]:
    """Collect tools used across all tutoring workflow rounds."""

    tools: List[str] = []

    scratchpad = response.get("scratchpad", [])

    if isinstance(scratchpad, list):
        for round_item in scratchpad:
            if not isinstance(round_item, dict):
                continue

            package = round_item.get("output_package", {}) or {}

            if not isinstance(package, dict):
                continue

            metadata = package.get("metadata", {}) or {}

            if not isinstance(metadata, dict):
                continue

            tool_names = metadata.get("tool_names", [])

            if not isinstance(tool_names, list):
                continue

            for tool_name in tool_names:
                if (
                    isinstance(tool_name, str)
                    and tool_name not in tools
                ):
                    tools.append(tool_name)

    if tools:
        return tools

    tool_selection = trace.get("tool_selection", {}) or {}

    if isinstance(tool_selection, dict):
        selected_tools = tool_selection.get(
            "selected_tools",
            [],
        )

        if isinstance(selected_tools, list):
            for tool_name in selected_tools:
                if (
                    isinstance(tool_name, str)
                    and tool_name not in tools
                ):
                    tools.append(tool_name)

    return tools


def build_trace_preview(
    response: Dict[str, Any],
    trace: Dict[str, Any],
    tools: List[str],
) -> Dict[str, Any]:
    """Build a compact trace preview for the demonstration."""

    validation = trace.get("validation_report", {}) or {}
    context = trace.get("collected_context_summary", {}) or {}
    memory_update = trace.get("memory_update_summary", {}) or {}

    if not isinstance(validation, dict):
        validation = {}

    if not isinstance(context, dict):
        context = {}

    if not isinstance(memory_update, dict):
        memory_update = {}

    return {
        "trace_id": (
            trace.get("trace_id")
            or response.get("trace_id")
        ),
        "task_type": trace.get("task_type"),
        "workflow_status": response.get("status"),
        "selected_tools": tools,
        "selection_strategy": trace.get(
            "selection_strategy"
        ),
        "reference_trace_id": trace.get(
            "reference_trace_id"
        ),
        "validation": {
            "status": validation.get("status"),
            "confidence_score": validation.get(
                "confidence_score"
            ),
            "failure_reason": validation.get(
                "failure_reason"
            ),
        },
        "attempts": trace.get(
            "attempts",
            response.get("attempts", 1),
        ),
        "recovery_used": trace.get(
            "recovery_used",
            response.get("recovery_used", False),
        ),
        "learner_context": {
            "learner_level": context.get(
                "learner_level"
            ),
            "is_weak_topic": context.get(
                "is_weak_topic"
            ),
            "retrieved_knowledge_chunks": context.get(
                "retrieved_knowledge_chunks"
            ),
        },
        "memory_update": {
            "status": trace.get(
                "memory_update_status"
            ),
            "diagnosed_gap": memory_update.get(
                "diagnosed_gap"
            ),
            "recommended_strategy": memory_update.get(
                "recommended_future_strategy"
            ),
        },
        "final_answer_status": trace.get(
            "final_answer_status"
        ),
    }


# ---------------------------------------------------------------------
# Interface helpers
# ---------------------------------------------------------------------

def render_manager_workflow() -> None:
    """Display the conceptual manager order used in the thesis."""

    first_row = st.columns(4)

    first_row[0].markdown(
        "**1. Task & Context Analyzer**"
    )
    first_row[1].markdown(
        "**2. Context Collector**"
    )
    first_row[2].markdown(
        "**3. Tool-Use Planner**"
    )
    first_row[3].markdown(
        "**4. Adaptive Tool Selector**"
    )

    second_row = st.columns(3)

    second_row[0].markdown(
        "**5. Tool Executor**"
    )
    second_row[1].markdown(
        "**6. Output Validator**"
    )
    second_row[2].markdown(
        "**7. Output Package Builder**"
    )


def format_optional_value(value: Any) -> str:
    """Return a readable value for optional trace fields."""

    if value is None or value == "":
        return "N/A"

    return str(value)


# ---------------------------------------------------------------------
# Input section
# ---------------------------------------------------------------------

st.title("OpenTutorAI Agentic Tutoring Demo")

st.caption(
    "Lightweight demonstration of the "
    "T2-Based Adaptive Tool Interaction Manager."
)

question = st.text_area(
    "Learner question",
    value="Explain convolution with a simple example.",
    height=110,
)

with st.expander("Demo option"):
    force_recovery = st.checkbox(
        "Force a controlled recovery attempt",
        value=False,
        help=(
            "Forces an incomplete first attempt to demonstrate "
            "validation and Failure Recovery."
        ),
    )

run_clicked = st.button(
    "Run tutoring workflow",
    type="primary",
    width="stretch",
)


# ---------------------------------------------------------------------
# Workflow execution
# ---------------------------------------------------------------------

if run_clicked:
    clean_question = question.strip()

    if not clean_question:
        st.error("Enter a learner question.")
    else:
        try:
            with st.spinner(
                "Running the agentic tutoring workflow..."
            ):
                response = (
                    AgenticCoreService()
                    .handle_request(
                        {
                            "request_type":
                                "personalized_tutoring",
                            "query": clean_question,
                            "learner_id": "demo_user",
                            "metadata": {
                                "source":
                                    "lightweight_demo_interface",
                                "force_recovery_test":
                                    force_recovery,
                            },
                        }
                    )
                )

                trace = load_trace(
                    response.get("trace_path")
                )

            st.session_state["demo_response"] = response
            st.session_state["demo_trace"] = trace

        except LLMProviderUnavailableError as error:
            st.error(
                f"LLM provider unavailable: {error}"
            )

        except ValueError as error:
            st.error(str(error))

        except Exception as error:
            st.error(
                f"Workflow execution failed: {error}"
            )


# ---------------------------------------------------------------------
# Results section
# ---------------------------------------------------------------------

response = st.session_state.get("demo_response")
trace = st.session_state.get("demo_trace", {})

if isinstance(response, dict):
    if not isinstance(trace, dict):
        trace = {}

    st.divider()

    validation = trace.get(
        "validation_report",
        {},
    ) or {}

    if not isinstance(validation, dict):
        validation = {}

    confidence = validation.get(
        "confidence_score"
    )

    if confidence is None:
        confidence = response.get("confidence")

    attempts = trace.get(
        "attempts",
        response.get("attempts", 1),
    )

    recovery_used = trace.get(
        "recovery_used",
        response.get("recovery_used", False),
    )

    tools = collect_tools(
        response=response,
        trace=trace,
    )

    metric_columns = st.columns(4)

    metric_columns[0].metric(
        "Status",
        response.get("status", "unknown"),
    )

    metric_columns[1].metric(
        "Confidence",
        confidence
        if confidence is not None
        else "N/A",
    )

    metric_columns[2].metric(
        "Attempts",
        attempts,
    )

    metric_columns[3].metric(
        "Recovery",
        "Used"
        if recovery_used
        else "Not used",
    )

    summary_tab, answer_tab, trace_tab = st.tabs(
        [
            "Execution Summary",
            "Final Answer",
            "Trace Preview",
        ]
    )

    # -----------------------------------------------------------------
    # Execution summary
    # -----------------------------------------------------------------

    with summary_tab:
        st.subheader("Manager workflow")

        render_manager_workflow()

        if recovery_used:
            st.info(
                "Validation triggered Failure Recovery before "
                "the successful attempt."
            )

        st.subheader("Selected tools")

        if tools:
            st.write(" · ".join(tools))
        else:
            st.write("No tools were recorded.")

        trace_id = (
            trace.get("trace_id")
            or response.get("trace_id")
        )

        if trace_id:
            st.caption(
                f"Tool Interaction Trace: {trace_id}"
            )

    # -----------------------------------------------------------------
    # Final learner-facing answer
    # -----------------------------------------------------------------

    with answer_tab:
        st.subheader("Final tutoring answer")

        final_answer = (
            response.get("answer")
            or response.get("final_answer")
        )

        st.markdown(
            final_answer
            or "No final tutoring answer was generated."
        )

    # -----------------------------------------------------------------
    # Readable trace preview
    # -----------------------------------------------------------------

    with trace_tab:
        preview = build_trace_preview(
            response=response,
            trace=trace,
            tools=tools,
        )

        st.subheader("Tool Interaction Trace preview")

        left_column, right_column = st.columns(2)

        with left_column:
            st.markdown(
                "**Trace ID**"
            )
            st.write(
                format_optional_value(
                    preview.get("trace_id")
                )
            )

            st.markdown(
                "**Task type**"
            )
            st.write(
                format_optional_value(
                    preview.get("task_type")
                )
            )

            st.markdown(
                "**Workflow status**"
            )
            st.write(
                format_optional_value(
                    preview.get("workflow_status")
                )
            )

            st.markdown(
                "**Selection strategy**"
            )
            st.write(
                format_optional_value(
                    preview.get("selection_strategy")
                )
            )

        with right_column:
            validation_preview = (
                preview.get("validation", {})
                or {}
            )

            st.markdown(
                "**Validation status**"
            )
            st.write(
                format_optional_value(
                    validation_preview.get("status")
                )
            )

            st.markdown(
                "**Confidence**"
            )
            st.write(
                format_optional_value(
                    validation_preview.get(
                        "confidence_score"
                    )
                )
            )

            st.markdown(
                "**Attempts**"
            )
            st.write(
                preview.get("attempts", 1)
            )

            st.markdown(
                "**Recovery used**"
            )
            st.write(
                "Yes"
                if preview.get("recovery_used")
                else "No"
            )

        st.markdown("**Selected tools**")

        selected_tools = preview.get(
            "selected_tools",
            [],
        )

        if selected_tools:
            st.write(
                " · ".join(selected_tools)
            )
        else:
            st.write("No tools were recorded.")

        learner_context = (
            preview.get("learner_context", {})
            or {}
        )

        st.markdown("**Learner context**")

        learner_level = format_optional_value(
            learner_context.get("learner_level")
        )

        weak_topic = (
            "Yes"
            if learner_context.get("is_weak_topic")
            else "No"
        )

        retrieved_chunks = learner_context.get(
            "retrieved_knowledge_chunks"
        )

        if retrieved_chunks is None:
            retrieved_chunks = "N/A"

        st.write(
            f"Level: {learner_level} · "
            f"Weak topic: {weak_topic} · "
            f"Retrieved chunks: {retrieved_chunks}"
        )

        memory_update = (
            preview.get("memory_update", {})
            or {}
        )

        diagnosed_gap = memory_update.get(
            "diagnosed_gap"
        )

        recommended_strategy = memory_update.get(
            "recommended_strategy"
        )

        if diagnosed_gap or recommended_strategy:
            st.markdown("**Memory update**")

            if diagnosed_gap:
                st.write(
                    f"Diagnosed gap: {diagnosed_gap}"
                )

            if recommended_strategy:
                st.write(
                    "Recommended strategy: "
                    f"{recommended_strategy}"
                )

        with st.expander(
            "View compact JSON trace"
        ):
            st.code(
                json.dumps(
                    preview,
                    indent=2,
                    ensure_ascii=False,
                ),
                language="json",
            )

        st.caption(
            "The complete Tool Interaction Trace remains stored "
            "under var/agentic_traces/."
        )
